apiVersion: apps/v1
kind: Deployment
metadata:
  name: ollama-ai  # ✅ your new name here
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ollama-ai  # ✅ same here
  template:
    metadata:
      labels:
        app: ollama-ai  # ✅ and here
    spec:
      containers:
        - name: ollama-ai  # ✅ container name can also match
          image: adibowvalley/3505
          ports:
            - containerPort: 11434
