apiVersion: v1
kind: Service
metadata:
  name: ollama-ai-service  # ✅ new service name
spec:
  selector:
    app: ollama-ai  # ✅ must match the updated deployment label
  ports:
    - protocol: TCP
      port: 80
      targetPort: 11434
  type: NodePort
