apiVersion: apps/v1
kind: Deployment
metadata:
  name: ollama-ai  
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ollama-ai  
  template:
    metadata:
      labels:
        app: ollama-ai  
    spec:
      containers:
        - name: ollama-ai  
          image: adibowvalley/3505
          ports:
            - containerPort: 11434
